#!/bin/sh
# Builds the app's default key file from a Redump .dkey archive.
#
#   sh scripts/prepare-keys.sh [archive.7z] [destination]
#
# Defaults to the archive mirrored under ~/Code and to
# "~/Library/Application Support/PS3QDD/keys.txt", which is where the app looks first.
# bsdtar ships with macOS and reads 7z natively, so no extra tools are needed.
set -u

# The key file is the whole point of the tool, and a wrong key corrupts an image silently
# rather than failing, so nothing this script writes is readable by anyone but its owner.
# Set once here so it covers the temp extraction directory as well as keys.txt.
umask 077

ARCHIVE=${1:-"$HOME/Code/ps3-aldostools-mirror/_staging/Resources/REDUMP_DKEY.7z"}
DEST=${2:-"$HOME/Library/Application Support/PS3QDD/keys.txt"}

die() {
    printf 'prepare-keys: %s\n' "$*" >&2
    exit 1
}

[ -f "$ARCHIVE" ] || die "no archive at $ARCHIVE"
command -v bsdtar >/dev/null 2>&1 || die "bsdtar not found"

# Extract into a fresh directory of its own rather than trusting the archive's paths.
WORK=$(mktemp -d) || die "could not create a temporary directory"
NEW=
trap 'rm -rf "$WORK"; [ -n "$NEW" ] && rm -f "$NEW"' EXIT INT TERM

bsdtar -xf "$ARCHIVE" -C "$WORK" --include '*.dkey' --no-same-owner --no-same-permissions 2>/dev/null \
    || bsdtar -xf "$ARCHIVE" -C "$WORK" --no-same-owner --no-same-permissions \
    || die "could not extract $ARCHIVE"

mkdir -p "$(dirname "$DEST")" || die "could not create $(dirname "$DEST")"

# Built beside the destination and moved into place at the end, so a wrong archive, or
# one whose entries are all rejected below, cannot truncate a keys.txt someone curated.
NEW="$DEST.new"

{
    printf '# PS3 disc keys. Generated by scripts/prepare-keys.sh from %s.\n' "$(basename "$ARCHIVE")"
    printf '# Redump .dkey files are 32 uppercase hex characters plus CRLF; the newline is stripped.\n'
    find "$WORK" -type f -name '*.dkey' | while IFS= read -r file; do
        title=$(basename "$file" .dkey)
        key=$(tr -d '\r\n' < "$file")
        # A title comes straight from the archive's filenames, so one containing a tab or
        # a newline would inject extra fields, or a whole extra line, into keys.txt.
        case "$title" in *[[:cntrl:]]*|"") continue ;; esac
        # Keep only well-formed entries: 32 hex characters and nothing else.
        case "$key" in
            *[!0-9A-Fa-f]*|"") continue ;;
        esac
        [ "${#key}" -eq 32 ] || continue
        printf '%s\t%s\n' "$title" "$key"
    done | LC_ALL=C sort
} > "$NEW" || die "could not write $NEW"

count=$(grep -c -v '^#' "$NEW" || true)
[ "$count" -gt 0 ] || die "no usable keys found in $ARCHIVE"

# `>` keeps the mode of an existing file, so this is what tightens a file made before.
chmod 600 "$NEW" || die "could not restrict permissions on $NEW"
mv -f "$NEW" "$DEST" || die "could not replace $DEST"
NEW=

printf 'Wrote %s keys to %s\n' "$count" "$DEST"
