#!/bin/sh
# Builds the app's default key file from a Redump .dkey archive.
#
#   sh scripts/prepare-keys.sh [archive.7z] [destination]
#
# Defaults to the archive mirrored under ~/Code and to
# "~/Library/Application Support/PS3QDD/keys.txt", which is where the app looks first.
# bsdtar ships with macOS and reads 7z natively, so no extra tools are needed.
set -u

ARCHIVE=${1:-"$HOME/Code/ps3-aldostools-mirror/_staging/Resources/REDUMP_DKEY.7z"}
DEST=${2:-"$HOME/Library/Application Support/PS3QDD/keys.txt"}

die() {
    printf 'prepare-keys: %s\n' "$*" >&2
    exit 1
}

[ -f "$ARCHIVE" ] || die "no archive at $ARCHIVE"
command -v bsdtar >/dev/null 2>&1 || die "bsdtar not found"

# Extract into a fresh directory of its own rather than trusting the archive's paths.
WORK=$(mktemp -d) || die "could not create a temporary directory"
trap 'rm -rf "$WORK"' EXIT INT TERM

bsdtar -xf "$ARCHIVE" -C "$WORK" --include '*.dkey' 2>/dev/null \
    || bsdtar -xf "$ARCHIVE" -C "$WORK" \
    || die "could not extract $ARCHIVE"

mkdir -p "$(dirname "$DEST")" || die "could not create $(dirname "$DEST")"

{
    printf '# PS3 disc keys. Generated by scripts/prepare-keys.sh from %s.\n' "$(basename "$ARCHIVE")"
    printf '# Redump .dkey files are 32 uppercase hex characters plus CRLF; the newline is stripped.\n'
    find "$WORK" -type f -name '*.dkey' | while IFS= read -r file; do
        title=$(basename "$file" .dkey)
        key=$(tr -d '\r\n' < "$file")
        # Keep only well-formed entries: 32 hex characters and nothing else.
        case "$key" in
            *[!0-9A-Fa-f]*|"") continue ;;
        esac
        [ "${#key}" -eq 32 ] || continue
        printf '%s\t%s\n' "$title" "$key"
    done | LC_ALL=C sort
} > "$DEST" || die "could not write $DEST"

count=$(grep -c -v '^#' "$DEST" || true)
[ "$count" -gt 0 ] || die "no usable keys found in $ARCHIVE"

printf 'Wrote %s keys to %s\n' "$count" "$DEST"
